name: Node.js CI

# Quando rodar a pipeline
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    # Variáveis de ambiente para o job
    env:
      DATABASE_URL: "file:./prisma/dev.db" # SQLite temporário para CI
      NODE_ENV: "test"

    steps:
      # 1️⃣ Pega o código do repositório
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Configura Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3️⃣ Instala dependências (respeita package-lock.json)
      - name: Install dependencies
        run: npm ci

      # 4️⃣ Cria arquivo .env (opcional, se Prisma precisar de leitura via dotenv)
      - name: Create .env
        run: echo "DATABASE_URL=file:./prisma/dev.db" > .env

      # 5️⃣ Gera Prisma Client
      - name: Generate Prisma client
        run: npx prisma generate

      # 6️⃣ Executa migrations (deploy seguro no CI)
      - name: Apply Prisma migrations
        run: npx prisma migrate deploy

      # 7️⃣ Roda os testes
      - name: Run tests
        run: npm test
